### ISSUE TITLE
Provide content for System Features

### ISSUE THREAD

**Issue by goodcodeguy** [dej1188/Software-Engineering-CSCIA360-PC-FALL-2022-PROJECT#4]
Document Template: https://github.com/rick4470/IEEE-SRS-Tempate

Provide content for Section 4 of the above IEEE SRS Template.

The features that should be documented are as follows:

- User submit a Youtube Video Link
- User can annotate plain text at a specific time in the video
- When you select the annotation it jumps the video to that point in time in the video
- As the video plays it highlights the current annotation based on time + n

**Comment by dej1188** [comment]
**4.1 Annotating Notes**
This high priority feature is the main function of the web based application for the note taking functionality.  The benefit of this feature is to provide the user with the access to annotate Youtube videos to learn more about how to be better players from coaches.  The security of the feature is defined by users having google accounts that can be traced back to for validity of a human user in case there is a potential hack.  The feature will accept all word requirements for a notated comment but only in English for the time being.  In the future it will be able to accept other languages from users to add notation.

**4.2 Notation at certain video sections**
The medium priority feature will allow a user to skip to certain time sections then input a comment at the specific time section they would like to add notation at.  For example if a user wants to add a comment at the 2:04 minute mark then the application will allow the user to do so.  The user cannot add a comment at 0:00 minutes.  The user will have to log into their YouTube/Google account to start accessing the feature to make notations on the video of their selection.  If a user does not sign in first then the option to add notes will not be available.  By adding notes at a specific point in a video, it will help expedite the process on the user’s end to be able to quickly and efficiently create the notes that they would like to add to help develop a player.

**4.3 Highlighting notes at certain non-overlapping time sections**
Users can add notes, but notes cannot overlap different time sections.  For example, if a note is made at 1:01 then a user cannot add a note at a time that overlaps with the time the note is added.  This will help decrease confusion from the learner that is reading the note added.  If a user tries to bypass the feature then an error will reflect that the user needs to adjust the time they are adding the notation.

**Comment by goodcodeguy** [comment]
added to document.
